### ISSUE TITLE
Does not appear to work with bootstrap.js 3.0.3

### ISSUE THREAD

**Issue by catskul** [ethaizone/Bootstrap-Confirmation#23]
results in "Uncaught TypeError: undefined is not a function " on line 59 of bootstrap-confirmation.js

problem does not occur in same environment when using bootstrap.js 3.2.0 

Tried with jquery 1.11.0, and 1.11.1

**Comment by papiermache** [comment]
Does not work for me either, no js errors, but nothing happens on click. using bs 3.3.2.  bummer.

**Comment by ddrmoscow** [comment]
The same issue with latest Bootstrap, 

The problem is  in bootstrap-tooltip.js. file.   "Confirmation plugin" was written for boostrap v2.+ , and works well  with boostarap v2+ and tooltip.js v2+ . 
Current bootstrap v3+  includes NEW tooltip.js v3 plugin, much different from previous v2+.

Here's the link to "Confirmation plugin" compatible with Twitter Bootstrap 3 : 
https://github.com/Tavicu/bootstrap-confirmation

Good luck
